import StoreProvider from './StoreProvider'
import Header from './components/header/index'
import { MantineProvider, ColorSchemeScript } from '@mantine/core'
import { Notifications } from '@mantine/notifications'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@mantine/core/styles.css'
import '@mantine/notifications/styles.css'
import { theme } from '../theme'
import Footer from '@/app/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript defaultColorScheme="dark" />
            </head>
            <body className={inter.className} suppressHydrationWarning={true}>
                <MantineProvider theme={theme} defaultColorScheme="dark">
                    <StoreProvider>
                        <Notifications />
                        <div className="flex flex-col h-screen w-screen">
                            <Header />
                            <div className="flex-grow h-full overflow-y-scroll">{children}</div>
                            <Footer />
                        </div>
                    </StoreProvider>
                </MantineProvider>
            </body>
        </html>
    )
}
